POST http://localhost:4000/classes/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlM2IxMmQ1MzI0MWEwYzg5YmUxZSIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJjbGF1ZGlvQGdtYWlsLmNvbSIsImlhdCI6MTY2OTM5MjAwOX0.OV5Qon7pD69oCsK-NCWY1uxHRKOTbNx8uD2RkNyr_zY

{
    "nombre": "Marketing Digital: Community Manager & Publicidad",
    "descripcion": "Aprenderás cómo crear un plan de Marketing Digital, y también a utilizar las principales herramientas de gestión para negocios digitales",
    "tipo": "Grupal",
    "categoria": "0",
    "frecuencia": "Semanal",
    "duracion": "2",
    "costo": "1800",
    "imagen": "https://tecreview.tec.mx/wp-content/uploads/2021/02/iStock-1222811180.jpg"
}

#########################################
GET http://localhost:4000/classes/

#########################################
GET http://localhost:4000/classes/63879a6bc997942b353a856e

#########################################
DELETE http://localhost:4000/classes/63879a6bc997942b353a856e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlM2IxMmQ1MzI0MWEwYzg5YmUxZSIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJjbGF1ZGlvQGdtYWlsLmNvbSIsImlhdCI6MTY3MDAzNDQ1Nn0.PVCtlgner8oQcMLaFxyKkQXFaJDaay5vGzwhQgcaj8U

#########################################

PUT http://localhost:4000/classes/unrollStudent/6380e6a32d53241a0c89be26
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlM2IxMmQ1MzI0MWEwYzg5YmUxZSIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJjbGF1ZGlvQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQwNjc1OH0.BcA17bx_3YwQSemc0HbRPN_6JPDd_Qm2q0svIU8Y7Dw

{
    "estudianteId": "638062a7be641a4ded3405bf"
}