POST http://localhost:4000/classes/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODAwNzcyNGY5ZmI5YTQ5YjIxMjczZCIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJtYXRpQGdtYWlsLmNvbSIsImlhdCI6MTY2OTMzNTE5Mn0.hpUeMOwdw0jOTTZetk_8StFNVuw7crGBf0WiPI_lGLo

{
    "nombre": "Guitarra basico",
    "descripcion": "Curso introductorio de guitarra",
    "tipo": "Presencial",
    "categoria": "Musica",
    "frecuencia": "Diario",
    "duracion": "2 horas",
    "costo": "2500",
    "imagen": "imagen de guitarrista"
}

#########################################
GET http://localhost:4000/classes/

#########################################
GET http://localhost:4000/classes/637ee294f2546ab21ac0ea04

#########################################
DELETE http://localhost:4000/classes/637ee22622f01fc88255a189
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2VlMjA4MjJmMDFmYzg4MjU1YTE4NiIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJtYXRpQGdtYWlsLmNvbSIsImlhdCI6MTY2OTI1OTc4OX0.ZmGYvxm8IGmblycYrG_taCdRCFTEPPs_8KWLu9eBVJs
