POST http://localhost:4000/classes/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODAyMjdhZGNlY2VmZDQyNzE5MDBkZCIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJhbmliYWxAZ21haWwuY29tIiwiaWF0IjoxNjY5MzU2NjQ4fQ.qtZrvAG4yQgEYqq7quXchJSaPOT0bvguB6WERq-Jc9Y

{
    "nombre": "Calculo diferencial e integral: aprende desde cero",
    "descripcion": "Conviertete en un genio del calculo matematico: Funciones, Estudio, Derivadas, Integrales… Y Mucho mas",
    "tipo": "Individual",
    "categoria": "0",
    "frecuencia": "Semanal",
    "duracion": "1.5",
    "costo": "800",
    "imagen": "http://img.youtube.com/vi/wuI5MFhvgsY/0.jpg"
}

#########################################
GET http://localhost:4000/classes/

#########################################
GET http://localhost:4000/classes/637ee294f2546ab21ac0ea04

#########################################
DELETE http://localhost:4000/classes/637ee22622f01fc88255a189
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2VlMjA4MjJmMDFmYzg4MjU1YTE4NiIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJtYXRpQGdtYWlsLmNvbSIsImlhdCI6MTY2OTI1OTc4OX0.ZmGYvxm8IGmblycYrG_taCdRCFTEPPs_8KWLu9eBVJs
