POST http://localhost:4000/comments
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODAzMjZiNmVkN2JkZDFkM2NjZDYzMyIsInJvbCI6ImFsdW1ubyIsImVtYWlsIjoiZmFjdW5kb0BnbWFpbC5jb20iLCJpYXQiOjE2NjkzNTM3ODZ9.kMNOwcwIE3vOBoyt34LGZ7xOf4wV96L9XfPshQ0gxaY

{
  "claseId": "63803b746ed7bdd1d3ccd63d",
  "descripcion": "Se entiende todo perfectamente, muy contento con la clase!"
}

###################################

GET http://localhost:4000/comments

###################################
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODAzNGNhNmVkN2JkZDFkM2NjZDYzOSIsInJvbCI6ImFsdW1ubyIsImVtYWlsIjoicGFtZWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTM1MTU4M30.wpiUjjJIeMWVce5EfFcFZd6C4-UBVKn2_oFEAZYxa2k

PUT http://localhost:4000/comments/"el id del comentario que quieras"

###################################

PUT  http://localhost:4000/comments/remove/638a88bde583517fb3d2ca68
