POST http://localhost:4000/hirings
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODAzNGNhNmVkN2JkZDFkM2NjZDYzOSIsInJvbCI6ImFsdW1ubyIsImVtYWlsIjoicGFtZWxhQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQwNjM4OX0.HaY0vuW7ATwrixkgCJT8w8p-odXijDJWb0M1bJmz0Vw

{
    "claseId": "6380e6a32d53241a0c89be26",
    "motivo": "Quisiera lograr que mi emprendimiento sea visible por mas gente",
    "horarioReferencia": "13-16"
}

#########################################

GET http://localhost:4000/hirings

#########################################
PUT http://localhost:4000/hirings/approve
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlM2IxMmQ1MzI0MWEwYzg5YmUxZSIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJjbGF1ZGlvQGdtYWlsLmNvbSIsImlhdCI6MTY2OTQwNjQ1Nn0.kQ1zknkQW8bjq4g-OUUgeIC4TQKyMoJf6ZzCAxONDps

{
    "contratacionId": "63811ed1dc3c89cba8aa2d90"
}