POST http://localhost:4000/teachers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlM2IxMmQ1MzI0MWEwYzg5YmUxZSIsInJvbCI6InByb2Zlc29yIiwiZW1haWwiOiJjbGF1ZGlvQGdtYWlsLmNvbSIsImlhdCI6MTY2OTM5MTYzOH0.tJGiEbmdXfncpDQkR2rccO9EcFNuLesFeyD7jOQuWnI

{
    "titulo": "Licenciado en marketing",
    "experiencia": "Mas de cuatro años de experiencia en la profesion"
}

#####################################

GET http://localhost:4000/teachers